# Generated by Django 5.1.3 on 2024-12-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_coop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profile_pictures/'),
        ),
    ]
