# Generated by Django 5.1.3 on 2024-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswaprofile',
            name='secondary_discipline',
            field=models.CharField(choices=[('Business Mathematics', 'Business Mathematics'), ('School of Applied STEM', 'School of Applied STEM')], default='School of Applied STEM', max_length=50),
        ),
        migrations.AlterField(
            model_name='mahasiswaprofile',
            name='primary_discipline',
            field=models.CharField(choices=[('Business Mathematics', 'Business Mathematics'), ('School of Applied STEM', 'School of Applied STEM')], default='School of Applied STEM', max_length=50),
        ),
    ]
