# Generated by Django 5.1.3 on 2024-11-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0003_mahasiswaprofile_secondary_discipline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswaprofile',
            name='secondary_discipline',
        ),
    ]
