# Generated by Django 5.1.3 on 2024-11-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0004_remove_mahasiswaprofile_secondary_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswaprofile',
            name='primary_discipline',
            field=models.CharField(choices=[('Business Mathematics', 'Business Mathematics'), ('School of Applied STEM', 'School of Applied STEM')], default='', max_length=50),
        ),
    ]
