# Generated by Django 5.1.3 on 2024-11-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0005_alter_mahasiswaprofile_primary_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanCOOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mahasiswa', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
                ('file_laporan', models.FileField(upload_to='laporan_coop/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
