# Generated by Django 5.1.1 on 2024-11-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0006_laporancoop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaporanCOOP',
        ),
    ]
