# Generated by Django 3.2 on 2024-11-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0008_companydata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswaprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
