# Generated by Django 5.1.3 on 2024-11-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0009_alter_mahasiswaprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswaprofile',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
