# Generated by Django 5.1.3 on 2024-11-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0010_alter_mahasiswaprofile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaporanCOOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_laporan', models.FileField(upload_to='laporan_coop/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporan_coop', to='mahasiswa_coop.mahasiswaprofile')),
            ],
        ),
    ]
