# Generated by Django 5.1.3 on 2024-11-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0011_websiteupdate_laporancoop'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='mahasiswa_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_data', to='mahasiswa_coop.mahasiswaprofile'),
        ),
    ]
