# Generated by Django 5.1.3 on 2024-12-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0012_alter_companydata_user'),
        ('mahasiswa_coop', '0012_companydata_mahasiswa_profile'),
    ]

    operations = [
    ]
