# Generated by Django 5.1.3 on 2024-12-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0014_alter_companydata_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteUpdate',
        ),
    ]
