# Generated by Django 5.1.3 on 2024-12-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0015_delete_websiteupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporancoop',
            name='judul_laporan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laporancoop',
            name='file_laporan',
            field=models.FileField(blank=True, null=True, upload_to='laporan_coop/'),
        ),
        migrations.AlterField(
            model_name='laporancoop',
            name='tanggal_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
