# Generated by Django 5.1.3 on 2024-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0015_delete_websiteupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='google_form_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
