# Generated by Django 5.1.3 on 2024-12-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa_coop', '0016_companydata_google_form_link'),
        ('mahasiswa_coop', '0016_laporancoop_judul_laporan_and_more'),
    ]

    operations = [
    ]
